#version: '3.8'

services:
  db:
    restart: always
    image: postgres:13-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: padichat_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   

  redis:
    image: redis:7.2.7-alpine
    restart: always
    ports:
      - "7379:7379"

  backend:
    build: 
      context: ./backend
      target: development
    command: >
      sh -c "chmod +x /app/entrypoint.sh &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/env/.env.local 
   
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend    
      target: development
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  celery:
    build:
      context: ./backend
      target: development
    command: >
      sh -c "chmod +x /app/entrypoint.sh &&
             celery -A core worker --loglevel=info"
    volumes:
      - ./backend:/app
    
    depends_on:
      - db
      - redis
  adminer:
        image: adminer
        restart: always      
        ports:
          - "8080:8080"
volumes:
  postgres_data: